name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Show current time
        run: |
          echo "The current time is $(date)."
      - name: Show current directory
        run: |
          echo "The current directory is $(pwd)."